In [1]:
%matplotlib inline

import numpy as np

In [2]:
a = np.array([1,2,3])
a.shape[0]

3

In [4]:
v = 1
v += 5
v

6

In [22]:
v = np.random.rand(5,3,2)
v[0]

array([[0.55544981, 0.71464739],
       [0.95667402, 0.61482448],
       [0.46294834, 0.34795157]])

In [21]:
for x in v:
    print(x,x.shape)
    print('-')

[[0.20530356 0.88410156]
 [0.7172586  0.90661387]
 [0.68209133 0.94636365]] (3, 2)
-
[[0.62291231 0.87806596]
 [0.01321362 0.1763838 ]
 [0.83803964 0.54522933]] (3, 2)
-
[[0.61472214 0.41025216]
 [0.15865792 0.09272519]
 [0.56164935 0.97206742]] (3, 2)
-
[[0.1983202  0.86732812]
 [0.68808169 0.768698  ]
 [0.62855377 0.47984099]] (3, 2)
-
[[0.57449397 0.47640619]
 [0.30571258 0.19474969]
 [0.13790184 0.65739557]] (3, 2)
-


In [23]:
v

array([[[0.55544981, 0.71464739],
        [0.95667402, 0.61482448],
        [0.46294834, 0.34795157]],

       [[0.3413808 , 0.30475546],
        [0.11718788, 0.91827546],
        [0.53279535, 0.55362059]],

       [[0.78624618, 0.70576737],
        [0.16171985, 0.648557  ],
        [0.0492439 , 0.45864466]],

       [[0.23091649, 0.48096747],
        [0.53811258, 0.55462205],
        [0.71630982, 0.08954884]],

       [[0.26330177, 0.07163944],
        [0.77700039, 0.91581691],
        [0.48050088, 0.29405458]]])

In [25]:
v[0,:,:]


array([[0.55544981, 0.71464739],
       [0.95667402, 0.61482448],
       [0.46294834, 0.34795157]])