In [1]:
%matplotlib inline

import numpy as np

In [6]:
a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
a

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [7]:
v = np.random.randn(2,3)
v

array([[ 0.79375831,  0.18495274, -2.52857041],
       [ 0.35362744, -2.13847901,  0.59369491]])

In [9]:
a @ v

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [21]:
for x in v:
    print(x,x.shape)
    print('-')

[[0.20530356 0.88410156]
 [0.7172586  0.90661387]
 [0.68209133 0.94636365]] (3, 2)
-
[[0.62291231 0.87806596]
 [0.01321362 0.1763838 ]
 [0.83803964 0.54522933]] (3, 2)
-
[[0.61472214 0.41025216]
 [0.15865792 0.09272519]
 [0.56164935 0.97206742]] (3, 2)
-
[[0.1983202  0.86732812]
 [0.68808169 0.768698  ]
 [0.62855377 0.47984099]] (3, 2)
-
[[0.57449397 0.47640619]
 [0.30571258 0.19474969]
 [0.13790184 0.65739557]] (3, 2)
-


In [27]:
v = np.arange(120).reshape(1,2,3,4,5)
v.shape[-2:]

(4, 5)

In [25]:
v[0,:,:]
np.einsum

array([[0.55544981, 0.71464739],
       [0.95667402, 0.61482448],
       [0.46294834, 0.34795157]])